### ISSUE TITLE
Match bug

### ISSUE THREAD

**Issue by lfilho** [fearmear/rexsub#1]
Hey man, nice work!

But i was giving it a go and it didn't work for one file...

Movie name was `Foo S02E06 Bar.avi`, subtitle was `foo.s02e06.dvdrip.xvid-bla.srt`, but subtitle file became `Foo S02E16 SomethinElse.avi` (`16` instead of `06`).

**Comment by fearmear** [comment]
Hey! Thanks for the report.
There was an issue with uppercase vs. lowercase S and E letters comparison. Fixed it in 1.0.5 https://github.com/fearmear/rexsub/commit/b3e29f6b7773ea0c7af0d87d5e73018b3bb0d1d0.
I think I'm going to improve matching further when I split digits and other characters when comparing filenames to make digits diff impact more on the comparison result.
